### ISSUE TITLE
How to use with dep?

### ISSUE THREAD

**Issue by twz123** [colinmarc/hdfs#158]
Apparently, the `v2` package structure is not compatible with `dep`. Any ideas how to use this project as a library in a project using dep for vendoring? I wasn't able to get it to work.

```
$ dep ensure -add github.com/colinmarc/hdfs/v2:github.com/colinmarc/hdfs@v2.0.0
Fetching sources...

Solving failure: No versions of github.com/colinmarc/hdfs met constraints:
        v2.0.0: Could not introduce github.com/colinmarc/hdfs@v2.0.0, as its subpackage github.com/colinmarc/hdfs/v2 is missing. (Package is required by (root).)
...
```

Maybe change the package structure again? :see_no_evil:

Side note: Thanks for your effort in creating and maintaining this project :-)

**Comment by colinmarc** [comment]
If dep doesn't support go modules, then this library doesn't support dep, unfortunately.

As I understand it, this is because of politics. See [the note here](https://golang.github.io/dep/blog/2018/07/25/announce-v0.5.0.html).

My recommendation is to move off of dep. Please let me know if I can help!

**Comment by twz123** [comment]
I'm not the maintainer of the project I'd like to integrate HDFS into. Will reach out to then and see what they think. Thanks.
