### ISSUE TITLE
Put support

### ISSUE THREAD

**Issue by grobie** [colinmarc/hdfs#5]
Hey,

great library! Looks very promising. I can see there is `CreateEmptyFile` method, but I can't see any other methods to write files to hdfs. Are there plans to add support for that, also for  put/copyFromLocal/moveFromLocal/etc. CLI commands?

Sorry if I missed the note about that.

Thanks

**Comment by mindscratch** [comment]
very interested in this as well, I appreciate the work.

**Comment by colinmarc** [comment]
@mindscratch thanks for the bump =) If you're interested on living on the edge, I think the tests are passing in the PR I referenced above (#12). It doesn't support failing over if a datanode dies, though.

**Comment by andrewlee302** [comment]
Hey, are you progressing on write supports? I am taking a HDFS-based distributed computing framework in golang, so i am eager to using your writing function instead of webREST interfaces.

**Comment by colinmarc** [comment]
Hey Andrew,

I Haven't made any progress recently, but if you check out the linked
branch the interfaces are there, and they work. The missing bits are
failover and comprehensive testing, but you could still develop against the
branch.

Sorry about the trouble!

**Comment by imoverclocked** [comment]
Hey @colinmarc,

  Thanks for the library and cli tools! It feels blazingly fast compared to using the standard hdfs cli or loading a jvm in general :)

  I see you wrote put support and I would like to use it. Since there is no support for datanode failover, what happens when a node does fail? Is there any kind of panic/error returned or do we currently just keep going like nothing happened?

Cheers,
-Tim

**Comment by colinmarc** [comment]
@imoverclocked If the test failures are any indication, I think you'll get some (byzantine) errors. Hopefully not a panic.

**Comment by colinmarc** [comment]
Closed in https://github.com/colinmarc/hdfs/pull/12
