### ISSUE TITLE
Don't close namenode connection on RPC failure

### ISSUE THREAD

**Issue by heartles** [colinmarc/hdfs#65]
When there is an RPC failure, the whole connection is closed, rendering the user unable to make any more calls until they make another call to hdfs.New(). 
This issue is actually mentioned with a TODO in the code itself: [rpc/namenode.go](https://github.com/colinmarc/hdfs/blob/1a4155475bdaa98f80f5e16c78a62f37de7c65f1/rpc/namenode.go):121
What would the desired behavior be? Keep the connection open? Recreate the connection? What happens if the reconnection fails?

**Comment by benclarkwood** [comment]
@colinmarc, I'm addressing this currently by checking if the returned error for `NamenodeConnection.readResponse` is `EOF` in `NamenodeConnection.Execute`. If it is an `EOF`, then it falls into the same retry logic as a standby exception. It seems like getting an `EOF` at this location is constrained to the case of:

1. You successfully connected to a namenode at some point
2. The connection to that namenode has since been severed

What do you think about making this specific inference?

**Comment by colinmarc** [comment]
It's no longer the case that the whole connection is closed - I'm not sure when that was fixed - so I'm going to close this.
