### ISSUE TITLE
Kerberos

### ISSUE THREAD

**Issue by wdavidw** [colinmarc/hdfs#8]
Are you supporting Kerberos, if not, is there any plan to introduce this functionnality.
d.

**Comment by colinmarc** [comment]
Hi David,

Good question! I don't really know what would be involved in that. I also don't really have a cluster set up to test with.

I'll leave this open for now - I'd love to hear any suggestions!

**Comment by Georce** [comment]
Hi Colinmarc
I have a cluster use kerberos auth
I test your hdfs cmd
![hdfskrb](https://cloud.githubusercontent.com/assets/10738505/11766170/a8092388-a1b5-11e5-9dd8-3a0bf6944180.jpg)

**Comment by colinmarc** [comment]
@Georce is that somewhere on the public internet for me to test with? Otherwise it'd be kind of hard to develop against =)

**Comment by Georce** [comment]
@colinmarc OK, I will provide an all in one CDH5 in kerberos with jenkins CI next week.
But no hdfs put cmd , your project be kind of hard to develop

**Comment by colinmarc** [comment]
That sounds super useful! In the tests, I use `hadoop fs -put` to populate the test data: https://github.com/colinmarc/hdfs/blob/master/setup_test_env.sh#L44-L45

**Comment by Georce** [comment]
@colinmarc
 I send email for you.  Is colinmarc@gmail.com ?

**Comment by colinmarc** [comment]
Yup, that's right.

**Comment by tristanwietsma** [comment]
Has there been any progress on this ticket? Looking for help?

**Comment by colinmarc** [comment]
I never ended up getting an email from @Georce - so I'm still blocked on the availability of a test cluster to develop against. That, and I really have no idea how kerberos works =)

**Comment by tristanwietsma** [comment]
Well, I've got a cluster at work, so I can try to carve out some time. It is secure, so I'll just mock it for test purposes. I think snakebite supports kerberos now, so I'll check that out and try to touch base in a week.

**Comment by colinmarc** [comment]
Oh amazing, thanks!

**Comment by tristanwietsma** [comment]
Glancing at the snakebite implementation and paraphrasing heavily...

- If `use_sasl` flag is set true,
    - Get the kerberos [user principal name](https://github.com/spotify/snakebite/blob/561a013faa02f392a2763022cefe1bda323ff926/snakebite/channel.py#L184-L189)
    - In the RPC headers, send the [auth protocol](https://github.com/spotify/snakebite/blob/561a013faa02f392a2763022cefe1bda323ff926/snakebite/channel.py#L235)
    - Authenticate via [sasl](https://github.com/spotify/snakebite/blob/561a013faa02f392a2763022cefe1bda323ff926/snakebite/channel.py#L235)
    - Business as usual.

**Comment by tristanwietsma** [comment]
Plot thickens in order to support encryption: spotify/snakebite#185

**Comment by Georce** [comment]
@colinmarc  What? I send you again. My email is wujian@wujian360.cn
![image](https://cloud.githubusercontent.com/assets/10738505/12676127/b269741a-c6ca-11e5-89b2-32a2d48d2785.png)

**Comment by colinmarc** [comment]
Huh, weird - I see it now, thank you!

**Comment by tristanwietsma** [comment]
Authentication/negotiation seems straightforward. Anyone grok the encryption workflow or know of a good working example? Snakebite is still deficient for this.

**Comment by tristanwietsma** [comment]
Any luck with the authentication part? I've been buried.

**Comment by colinmarc** [comment]
Haven't looked at all, sorry =(. Also pretty buried.

**Comment by didip** [comment]
Hi all, sorry for digging up an old ticket, is there still interest in Kerberos?

**Comment by colinmarc** [comment]
I'd still love to have this, but don't really have the time, context or environment to add the feature.

**Comment by lomik** [comment]
@colinmarc, FYI

I've implemented Kerberos authentification here https://github.com/lomik/hdfs/commit/bae39b4ca875727109cbe82a9da8df4054e03307

But this implementation is not native and requires go-sasl library (cgo wrapper for Cyrus SASL) :(

**Comment by wrouesnel** [comment]
It might be an idea to gate @lomik 's code under a build tag, since it's the right basic approach we're just lacking a go-native GSSAPI library to support it.

**Comment by mxk1235** [comment]
@lomik does your implementation support keytabs?

thanks in advance.

**Comment by lomik** [comment]
@mxk1235,  keytabs are not supported

**Comment by Shastick** [comment]
We have a go-hdfs implementation working with Kerberos at https://github.com/Sqooba/hdfs (using a pure go kerberos library)

Haven't done a PR yet as the code probably deserves a few cleanups and that we have not figured out automated testing yet (and we'd be curious to hear any suggestions about that matter)

Development was done against a [Kerby KDC](http://directory.apache.org/kerby/) which is reasonably easy to setup and a hdfs mini cluster from https://github.com/sakserv/hadoop-mini-clusters/

(We attempted to use a miniKDC from the above repo, but they currently have an issue: https://github.com/sakserv/hadoop-mini-clusters/issues/51)

I'm not sure of the best path to follow for testing: 
  - run the whole test suite with Kerberos on?
  - just add a simple test case with Kerberos turned on, and leave it off otherwise?
  - run the tests with Kerberos on and off?

I'm only mildly familiar with travis CI, and enabling/disabling Kerberos might require changing/reloading the Hadoop environment entirely (unless we can tell it to accept both plaintext and SASL auth, have not checked if that is possible yet)

Anyway, in the meantime, we have a few persons using the code daily and it runs smoothly.

Feedback and comments more than welcome.

**Comment by colinmarc** [comment]
link to the PR for reference: #99

**Comment by xxh2000** [comment]
Kerbores security is common in Hadoop， without this support，it is very inconvenient to use this lib。

**Comment by colinmarc** [comment]
There is now an internal PR that adds support for Kerberos: #133 

If you're running Kerberos in production, please test it out and let me know if it works!

**Comment by colinmarc** [comment]
Fixed in #133. I'll do a version release soon.
